In [5]:
import numpy as np 
import pandas as pd 
import seaborn as sns

In [6]:
df = sns.load_dataset('tips')
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [9]:
df.groupby('sex')[['total_bill']].mean()

        total_bill
sex
Male     20.744076
Female   18.056897

In [19]:
# my way to find out the smoker people spend.

new = df[(df['smoker'] == 'Yes')]
new.groupby('sex')[['total_bill']].mean()

        total_bill
sex
Male     22.284500
Female   17.977879

In [20]:
# sir way :

df.groupby(['sex', 'smoker'])[['total_bill']].mean().unstack()

       total_bill
smoker        Yes         No
sex
Male    22.284500  19.791237
Female  17.977879  18.105185

In [22]:
# aggfunc() :

df.pivot_table(index='sex', columns='smoker', values='total_bill', aggfunc='sum')

smoker      Yes       No
sex
Male    1337.07  1919.75
Female   593.27   977.68

In [28]:
# all cols together :
df.pivot_table(index='sex', columns='smoker', values=['size', 'total_bill']) 
# we need to use values= in new version.

            size           total_bill
smoker       Yes        No        Yes         No
sex
Male    2.500000  2.711340  22.284500  19.791237
Female  2.242424  2.592593  17.977879  18.105185

In [ ]:
# multidimentional :
df.pivot_table(index=['sex','smoker'],
               columns=['day','time'],
               values=['size','tip','total_bill'],
               aggfunc={'size':'mean', 'tip':'max', 'total_bill':'sum'})

                   size                                               tip  \
day                Thur              Fri              Sat       Sun  Thur
time              Lunch Dinner     Lunch Dinner    Dinner    Dinner Lunch
sex    smoker
Male   Yes     2.300000    NaN  1.666667    2.4  2.629630  2.600000  5.00
       No      2.500000    NaN       NaN    2.0  2.656250  2.883721  6.70
Female Yes     2.428571    NaN  2.000000    2.0  2.200000  2.500000  5.00
       No      2.500000    2.0  3.000000    2.0  2.307692  3.071429  5.17

                                                total_bill                \
day                    Fri           Sat    Sun       Thur           Fri
time          Dinner Lunch Dinner Dinner Dinner      Lunch Dinner  Lunch
sex    smoker
Male   Yes       NaN  2.20   4.73  10.00    6.5     191.71    NaN  34.16
       No        NaN   NaN   3.50   9.00    6.0     369.73    NaN    NaN
Female Yes       NaN  3.48   4.30   6.50    4.0     134.53    NaN  39.78
       No        3.0  3.00   3.25   4.67    5.2     381.58  18.78  15.98


day                       Sat     Sun
time           Dinner  Dinner  Dinner
sex    smoker
Male   Yes     129.46  589.62  392.12
       No       34.95  637.73  877.34
Female Yes      48.80  304.00   66.16
       No       22.75  247.05  291.54

In [33]:
# margins :
df.pivot_table(index='sex', columns='smoker', values='total_bill', aggfunc='sum', margins=True)

smoker      Yes       No      All
sex
Male    1337.07  1919.75  3256.82
Female   593.27   977.68  1570.95
All     1930.34  2897.43  4827.77

In [ ]:
# plotting Graphs :