In [46]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt


df = pd.read_csv('/workspaces/Python-For-Data-Science/Database from Kaggle/netflix_titles.csv')
df.sample(20)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
6960,s6961,Movie,Hera Pheri,Prakash Mehra,"Amitabh Bachchan, Vinod Khanna, Saira Banu, Su...",India,"December 31, 2019",1976,TV-14,156 min,"Action & Adventure, Comedies, Dramas",The bond between two crooks and best friends i...
3701,s3702,Movie,Super Deluxe,Thiagarajan Kumararaja,"Vijay Sethupathi, Fahadh Faasil, Samantha Ruth...",India,"June 29, 2019",2019,TV-MA,176 min,"Comedies, Dramas, International Movies","Sex, stigma and spirituality merge in these ec..."
3794,s3795,TV Show,Historical Roasts,NaN,"Jeff Ross, Bob Saget, James Adomian, Rachel Fe...",United States,"May 27, 2019",2019,TV-MA,1 Season,"Stand-Up Comedy & Talk Shows, TV Comedies","""Roastmaster General"" Jeff Ross and a slew of ..."
7174,s7175,Movie,Kay Dyache Bola,Chandrakant Kulkarni,"Makarand Anaspure, Akshay Pendse, Umesh Kamat,...",India,"January 1, 2018",2005,TV-14,133 min,"Comedies, Dramas, International Movies","Wrongfully accused of murder, two students' la..."
5460,s5461,Movie,Oh Darling Yeh Hai India,Ketan Mehta,"Shah Rukh Khan, Deepa Sahi, Javed Jaffrey, Anu...",India,"June 1, 2017",1995,TV-14,154 min,"Action & Adventure, Comedies, International Mo...",A penniless actor new to Mumbai and a beautifu...
8408,s8409,Movie,The lynx,Stanisław Różewicz,"Jerzy Radziwiłowicz, Franciszek Pieczka, Piotr...",Poland,"October 1, 2019",1982,TV-14,82 min,"Dramas, International Movies",A priest's duties are tested when a young guer...
3895,s3896,Movie,Grass Is Greener,Fab Five Freddie,NaN,NaN,"April 20, 2019",2019,TV-MA,98 min,"Documentaries, Music & Musicals",It lit up jazz and hip-hop – and ignited a war...
5356,s5357,TV Show,Love Storm,NaN,"Chris Wu, Chen Yu, Greg Han, Esther Yeh, Yeh C...",NaN,"August 1, 2017",2016,TV-14,1 Season,"International TV Shows, Romantic TV Shows, TV ...",Three grown siblings must rethink their idea o...
7895,s7896,Movie,Rounders,John Dahl,"Matt Damon, Edward Norton, John Turturro, Gret...",United States,"November 1, 2019",1998,R,121 min,Dramas,"A law student befriends and ""befoes"" a fellow ..."
4186,s4187,Movie,"Abdullah, The Final Witness",Hashim Nadeem Khan,"Sajid Hasan, Hameed Sheikh, Habibullah Panezai...",Pakistan,"January 15, 2019",2016,TV-14,88 min,"Dramas, International Movies","Inspired by real events, this drama follows a ..."
2798,s2799,Movie,3022,John Suits,"Omar Epps, Kate Walsh, Miranda Cosgrove, Angus...",United States,"March 19, 2020",2019,R,91 min,"Independent Movies, Sci-Fi & Fantasy, Thrillers",Stranded when the Earth is suddenly destroyed ...
298,s299,Movie,Quam's Money,Kayode Kasum,"Falz, Nse Ikpe-Etim, Williams Uchemba, Toni To...",Nigeria,"August 6, 2021",2020,TV-MA,115 min,"Comedies, Dramas, International Movies","In this sequel to ""New Money,"" Quam, a securit..."
7909,s7910,Movie,Russell Peters: Notorious,Dave Higby,Russell Peters,United States,"October 14, 2013",2013,NR,72 min,Stand-Up Comedy,Global comedy star Russell Peters leaves no et...
8099,s8100,Movie,Straight Up,James Sweeney,"James Sweeney, Katie Findlay, Randall Park, Hi...",United States,"June 26, 2020",2020,TV-MA,96 min,"Comedies, Independent Movies, LGBTQ Movies",When a gay brainiac with OCD questions his ide...
746,s747,Movie,Awake,Mark Raso,"Gina Rodriguez, Ariana Greenblatt, Frances Fis...",United States,"June 9, 2021",2021,TV-MA,97 min,"Dramas, Thrillers",After a global event wipes out humanity's abil...
3281,s3282,TV Show,The Stranded,NaN,"Papangkorn Lerkchaleampote, Chayanit Chansanga...",Thailand,"November 15, 2019",2019,TV-MA,1 Season,"International TV Shows, TV Action & Adventure,...","Trapped on an island destroyed by a tsunami, t..."
5485,s5486,Movie,Ram Jaane,Rajiv Mehra,"Shah Rukh Khan, Juhi Chawla, Vivek Mushran, Pa...",India,"May 15, 2017",1995,TV-14,142 min,"Dramas, International Movies, Music & Musicals","Two boyhood pals – one righteous, the other a ..."
3513,s3514,Movie,Los Tigres del Norte at Folsom Prison,Tom Donahue,Los Tigres del Norte,United States,"September 15, 2019",2019,TV-PG,64 min,"Documentaries, International Movies, Music & M...",The beloved norteño band Los Tigres del Norte ...
4990,s4991,Movie,Stretch Armstrong: The Breakout,Victor Cook,"Scott Menville, Steven Yeun, Ogie Banks, Nazne...",United States,"March 13, 2018",2018,TV-Y7,104 min,Children & Family Movies,Villains are rampaging through Charter City an...
5945,s5946,Movie,In Defense of a Married Man,Joel Oliansky,"Judith Light, Michael Ontkean, Jerry Orbach, P...",United States,"October 1, 2011",1990,TV-14,94 min,Dramas,A lawyer's husband is having an affair. When h...

In [47]:
df.isnull().sum()

show_id            0
type               0
title              0
director        2634
cast             825
country          831
date_added        10
release_year       0
rating             4
duration           3
listed_in          0
description        0
dtype: int64

In [48]:
df.shape[0]

8807

In [49]:
df.columns

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in', 'description'],
      dtype='str')

In [50]:
df[['director','cast', 'country']].isnull().sum()

director    2634
cast         825
country      831
dtype: int64

In [55]:
df['director']= df['director'].replace(np.nan, 'Unknown')
df['cast']= df['cast'].replace(np.nan, 'Unknown')
df['country']= df['country'].replace(np.nan, 'Unknown')

df.dropna(subset='date_added', inplace=True)
df.dropna(subset='duration', inplace=True)
df.dropna(subset='rating', inplace=True)

df.dropna(inplace=True) # for final clean !
df.head(10)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,Unknown,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,Unknown,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",Unknown,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,Unknown,Unknown,Unknown,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,Unknown,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
5,s6,TV Show,Midnight Mass,Mike Flanagan,"Kate Siegel, Zach Gilford, Hamish Linklater, H...",Unknown,"September 24, 2021",2021,TV-MA,1 Season,"TV Dramas, TV Horror, TV Mysteries",The arrival of a charismatic young priest brin...
6,s7,Movie,My Little Pony: A New Generation,"Robert Cullen, José Luis Ucha","Vanessa Hudgens, Kimiko Glenn, James Marsden, ...",Unknown,"September 24, 2021",2021,PG,91 min,Children & Family Movies,Equestria's divided. But a bright-eyed hero be...
7,s8,Movie,Sankofa,Haile Gerima,"Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D...","United States, Ghana, Burkina Faso, United Kin...","September 24, 2021",1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies","On a photo shoot in Ghana, an American model s..."
8,s9,TV Show,The Great British Baking Show,Andy Devonshire,"Mel Giedroyc, Sue Perkins, Mary Berry, Paul Ho...",United Kingdom,"September 24, 2021",2021,TV-14,9 Seasons,"British TV Shows, Reality TV",A talented batch of amateur bakers face off in...
9,s10,Movie,The Starling,Theodore Melfi,"Melissa McCarthy, Chris O'Dowd, Kevin Kline, T...",United States,"September 24, 2021",2021,PG-13,104 min,"Comedies, Dramas",A woman adjusting to life after a loss contend...

In [56]:
df.isnull().sum() # ok so now our data has been cleaned !

show_id         0
type            0
title           0
director        0
cast            0
country         0
date_added      0
release_year    0
rating          0
duration        0
listed_in       0
description     0
dtype: int64