In [23]:
import pandas as pd
import numpy as np

In [24]:
df = pd.read_csv('/workspaces/Python-For-Data-Science/Database from Kaggle/Messy_Employee_dataset.csv')

df.sample(20)

,Employee_ID,First_Name,Last_Name,Age,Department_Region,Status,Join_Date,Salary,Email,Phone,Performance_Score,Remote_Work
777,EMP1777,Frank,Garcia,40.0,Cloud Tech-Florida,Pending,5/12/2020,70498.29,frank.garcia@example.com,-5515122945,Good,True
58,EMP1058,David,Williams,35.0,Finance-Texas,Pending,11/7/2021,93620.88,david.williams@example.com,-54522800,Good,False
972,EMP1972,Bob,Smith,NaN,Finance-Florida,Active,8/24/2021,96346.53,bob.smith@example.com,-7876553006,Average,True
1009,EMP2009,David,Garcia,NaN,Finance-Illinois,Pending,6/11/2024,62603.98,david.garcia@example.com,-7315391148,Poor,False
929,EMP1929,Alice,Smith,35.0,Finance-New York,Pending,10/14/2024,79934.83,alice.smith@example.com,-3693626893,Average,True
296,EMP1296,Bob,Miller,NaN,Cloud Tech-Texas,Pending,11/1/2022,64150.97,bob.miller@example.com,-23142899,Good,True
679,EMP1679,Grace,Johnson,40.0,Admin-California,Active,5/14/2022,93772.61,grace.johnson@example.com,-4256529059,Poor,False
91,EMP1091,Bob,Brown,35.0,Finance-New York,Inactive,3/13/2023,92723.22,bob.brown@example.com,-9070562607,Excellent,True
987,EMP1987,Eva,Brown,25.0,HR-Illinois,Inactive,7/5/2024,65812.02,eva.brown@example.com,-3963845268,Average,True
938,EMP1938,Grace,Miller,30.0,Finance-Nevada,Pending,5/16/2021,51990.98,grace.miller@example.com,-5143776935,Excellent,True
661,EMP1661,Alice,Williams,40.0,Cloud Tech-California,Pending,5/25/2023,63927.07,alice.williams@example.com,-1553334263,Good,True
310,EMP1310,Frank,Garcia,30.0,HR-New York,Pending,12/3/2022,65472.99,frank.garcia@example.com,-2105524727,Good,False
130,EMP1130,Frank,Brown,25.0,Finance-Texas,Pending,7/24/2022,51074.33,frank.brown@example.com,-7303379336,Excellent,True
428,EMP1428,David,Smith,NaN,Admin-Florida,Inactive,5/2/2020,118079.15,david.smith@example.com,-3170876013,Good,True
191,EMP1191,Heidi,Williams,40.0,Sales-Illinois,Inactive,10/26/2023,114690.80,heidi.williams@example.com,-1498282466,Poor,True
818,EMP1818,Alice,Brown,30.0,DevOps-New York,Inactive,12/24/2022,70405.23,alice.brown@example.com,-8065625903,Poor,True
162,EMP1162,Bob,Garcia,40.0,Finance-California,Pending,4/30/2023,57633.78,bob.garcia@example.com,-8597779013,Poor,True
910,EMP1910,Bob,Williams,30.0,Finance-Texas,Active,3/11/2022,112856.21,bob.williams@example.com,-4281785227,Poor,False
630,EMP1630,Alice,Smith,30.0,Finance-Nevada,Active,7/5/2024,56376.20,alice.smith@example.com,-1312840332,Average,True
212,EMP1212,Charlie,Jones,35.0,Finance-Illinois,Active,8/28/2024,80623.08,charlie.jones@example.com,-5671649327,Excellent,True

In [ ]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Employee_ID        1020 non-null   str
 1   First_Name         1020 non-null   str
 2   Last_Name          1020 non-null   str
 3   Age                809 non-null    float64
 4   Department_Region  1020 non-null   str
 5   Status             1020 non-null   str
 6   Join_Date          1020 non-null   str
 7   Salary             996 non-null    float64
 8   Email              1020 non-null   str
 9   Phone              1020 non-null   int64
 10  Performance_Score  1020 non-null   str
 11  Remote_Work        1020 non-null   bool
dtypes: bool(1), float64(2), int64(1), str(8)
memory usage: 88.8 KB

In [ ]:
df.head()

,Employee_ID,First_Name,Last_Name,Age,Department_Region,Status,Join_Date,Salary,Email,Phone,Performance_Score,Remote_Work
0,EMP1000,Bob,Davis,25.0,DevOps-California,Active,4/2/2021,59767.65,bob.davis@example.com,-1651623197,Average,True
1,EMP1001,Bob,Brown,NaN,Finance-Texas,Active,7/10/2020,65304.66,bob.brown@example.com,-1898471390,Excellent,True
2,EMP1002,Alice,Jones,NaN,Admin-Nevada,Pending,12/7/2023,88145.90,alice.jones@example.com,-5596363211,Good,True
3,EMP1003,Eva,Davis,25.0,Admin-Nevada,Inactive,11/27/2021,69450.99,eva.davis@example.com,-3476490784,Good,True
4,EMP1004,Frank,Williams,25.0,Cloud Tech-Florida,Active,1/5/2022,109324.61,frank.williams@example.com,-1586734256,Poor,False

In [ ]:
# insert two columns and dropped the older one.

df.insert(1, 'Name', df['First_Name'] + ' ' + df['Last_Name'])
df.drop(columns=['First_Name', 'Last_Name'], inplace=True)
df

,Employee_ID,Name,Age,Department_Region,Status,Join_Date,Salary,Email,Phone,Performance_Score,Remote_Work
0,EMP1000,Bob Davis,25.0,DevOps-California,Active,4/2/2021,59767.65,bob.davis@example.com,-1651623197,Average,True
1,EMP1001,Bob Brown,NaN,Finance-Texas,Active,7/10/2020,65304.66,bob.brown@example.com,-1898471390,Excellent,True
2,EMP1002,Alice Jones,NaN,Admin-Nevada,Pending,12/7/2023,88145.90,alice.jones@example.com,-5596363211,Good,True
3,EMP1003,Eva Davis,25.0,Admin-Nevada,Inactive,11/27/2021,69450.99,eva.davis@example.com,-3476490784,Good,True
4,EMP1004,Frank Williams,25.0,Cloud Tech-Florida,Active,1/5/2022,109324.61,frank.williams@example.com,-1586734256,Poor,False
...,...,...,...,...,...,...,...,...,...,...,...
1015,EMP2015,David Miller,30.0,HR-California,Active,8/19/2023,NaN,david.miller@example.com,-3546212759,Good,True
1016,EMP2016,David Johnson,30.0,Cloud Tech-Texas,Inactive,11/7/2021,100215.06,david.johnson@example.com,-2508261122,Good,True
1017,EMP2017,Charlie Williams,40.0,Finance-New York,Active,10/4/2023,114587.11,charlie.williams@example.com,-1261632487,Average,False
1018,EMP2018,Alice Garcia,30.0,HR-Florida,Inactive,12/16/2024,71318.79,alice.garcia@example.com,-8995729892,Good,True
1019,EMP2019,Heidi Jones,30.0,DevOps-Illinois,Pending,2/22/2021,77764.24,heidi.jones@example.com,-7629745492,Average,False